#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Raghuveer Dendukuri
# kit-status.sh — render the generated status view. Never hand-edit the output.
set -uo pipefail
. "$(dirname "$0")/kit-lib.sh"

ROOT=$(kit_root) || exit 0
kit_active "$ROOT" || exit 0
PROFILE=$(kit_profile "$ROOT")
STATE_DIR=$(kit_cfg "$PROFILE" paths.state ".project")
OUT="$ROOT/$(kit_cfg "$PROFILE" paths.status "STATUS.generated.md")"
DB="$ROOT/$STATE_DIR/index.db"

# `bash <script>` rather than a bare invocation: tooling/ arrives without the exec bit in
# some packagings, and a status run that silently skips its own rebuild lands squarely in
# the failure guarded against just below.
if [ ! -f "$DB" ]; then
  bash "$(dirname "$0")/kit-index.sh" >/dev/null ||
    { kit_warn "index build failed — refusing to write a status file"; exit 1; }
fi

# Prove the index is readable before rendering anything. Every query below degrades to
# empty on a missing or corrupt DB, and an empty STATUS.generated.md is indistinguishable
# from an idle repo -- a measurement failure wearing the costume of good news. The trailer
# warning at the bottom cannot catch this either, since TOTAL would default to 0.
if ! sqlite3 "$DB" "SELECT COUNT(*) FROM task;" >/dev/null 2>&1; then
  kit_warn "index at ${DB#$ROOT/} is missing or unreadable; run kit-index.sh"
  exit 1
fi

q() { sqlite3 -noheader -separator '|' "$DB" "$1" 2>/dev/null; }

TOTAL=$(q "SELECT value FROM meta WHERE key='commits_total';");    TOTAL=${TOTAL:-0}
UNTAG=$(q "SELECT value FROM meta WHERE key='commits_untagged';"); UNTAG=${UNTAG:-0}
EXEMPTN=$(q "SELECT value FROM meta WHERE key='commits_exempt';");  EXEMPTN=${EXEMPTN:-0}
# meta holds TEXT; a non-numeric value would make the arithmetic at the bottom fail.
case "$TOTAL" in ''|*[!0-9]*) TOTAL=0 ;; esac
case "$UNTAG" in ''|*[!0-9]*) UNTAG=0 ;; esac
case "$EXEMPTN" in ''|*[!0-9]*) EXEMPTN=0 ;; esac
# The denominator is commits that were REQUIRED to carry a Task-Id, not every commit.
# git.trivial_pattern exempts chore/docs/style at the commit-msg hook, so counting them
# here made the warning permanent on a repository obeying the rule exactly. Guard against
# a stale index written before commits_exempt existed, where EXEMPTN reads 0.
REQUIRED=$(( TOTAL - EXEMPTN )); [ "$REQUIRED" -lt 0 ] && REQUIRED=0

{
printf '<!-- GENERATED by kit-status.sh. Do not edit. Source of truth: whatever ingest.* selects — task files and git trailers by default. -->\n'
printf '# Status\n\n'

printf '## Open\n\n'
OPEN=$(q "SELECT t.id||'  '||COALESCE(NULLIF(n.title,''),t.id)||'  ['||COALESCE(NULLIF(t.tier,''),'untiered')||']'||CASE WHEN t.blocked_by<>'' THEN '  blocked-by '||t.blocked_by ELSE '' END||CASE WHEN COALESCE(t.owner,'')<>'' THEN '  @'||t.owner ELSE '' END
          FROM task t JOIN node n ON n.id=t.id
          WHERE t.state NOT IN (SELECT state FROM state_class WHERE is_closed = 1) ORDER BY t.state, t.id;")
[ -n "$OPEN" ] && printf '%s\n' "$OPEN" | sed 's/^/- /' || printf '_none_\n'

printf '\n## Closed\n\n'
# THREE COUNTS, NOT TWO, AND cancelled IS WHY THE THIRD EXISTS. `abandoned` judges the ATTEMPT --
# we stopped; `cancelled` judges the WORK -- it should not be done at all. Reporting them as one
# number is the misread docs/adr/0008 was written to remove: a backlog whose irrelevant items were
# filed as abandoned reads as a project that abandons a great deal.
printf -- '- %s completed, %s cancelled, %s abandoned\n' \
  "$(q "SELECT COUNT(*) FROM task WHERE state='completed';")" \
  "$(q "SELECT COUNT(*) FROM task WHERE state='cancelled';")" \
  "$(q "SELECT COUNT(*) FROM task WHERE state='abandoned';")"
# The dilution used to be stated here, in prose, because the escape-rate table had no `measured`
# column to carry it. It now does, and the row names the excluded count in the place a reader is
# actually comparing numbers. Two statements of one fact drift apart -- this one had already gone
# stale, still claiming "nothing is excluded" after the exclusion existed.
# LEGACY SPELLINGS, COUNTED SO THEY DRAIN. Task files may carry `open`/`done`/`progress` forever
# and the indexer resolves them; silence about that is how two vocabularies become permanent. This
# is a number to watch fall, not a warning to act on -- no work is required to reduce it.
_TASKDIR=$(kit_cfg "$PROFILE" paths.tasks ".project/tasks")
_LEG=0; _LEGBREAK=""
for _p in $(kit_state_legacy); do
  _n=$(grep -l "^state: ${_p%%:*}\$" "$ROOT/$_TASKDIR"/*.md 2>/dev/null | wc -l | tr -d ' ')
  [ "${_n:-0}" -gt 0 ] && _LEGBREAK="$_LEGBREAK ${_n}x ${_p%%:*}->${_p##*:},"
  _LEG=$((_LEG + _n))
done
if [ "${_LEG:-0}" -gt 0 ]; then
  # BROKEN DOWN BY VALUE, not just totalled. A bare count says a debt exists; naming which
  # spellings and how many is what someone can act on, and it is what makes the number fall
  # visibly rather than sit there. Nothing here is broken -- the index resolves every one of
  # them -- so this is a remediation backlog, deliberately not a warning.
  printf -- '- %s task file(s) still write a legacy state name:%s resolved on read (ADR 0008)\n' \
    "$_LEG" "$(printf '%s' "$_LEGBREAK" | sed 's/,$//')"
  printf -- '  Not an error, and no work is required. Rewriting them to the canonical value is\n'
  printf -- '  safe at any time and is tracked by `T-20260822-legacy-state-spellings-in-task-files-sho`.\n'
fi

# An id referenced by history that no task file backs. The indexer no longer invents a task for
# it -- that is what put a typo'd id in the Open list, the backlog count and an escape-rate
# denominator, permanently, from one pushed commit. Dropping it silently would trade a visible
# wrong number for an invisible one, so it is named here with the commit that introduced it.
#
# NOT EXISTS rather than NOT IN: `NOT IN` against a set holding a NULL is NULL for every row,
# never true, and would empty this section without a word. That is not hypothetical in this
# file -- the residue count below shipped with exactly that defect and a review caught it.
#
# Two origins, and they need different repairs, so the report shows which rather than guessing.
# An id carrying events came from a git trailer: the introducing commit is where the typo is,
# and the event kinds are the evidence for whether this was a stray reference or a task that had
# a life and lost its file. An id with NO events was never in history at all -- it came from
# another task's `blocked_by:` frontmatter, where "correct the trailer" is advice about a trailer
# that does not exist, so the declaring FILE is named instead.
#
# The kinds are printed rather than interpreted. `done` on a fileless id says a task completed
# and its file went missing; a lone `progress` says someone typed an id wrong. Both readings are
# usually right and neither is reliable enough to assert, so the reader gets the evidence.
#
# Ids are wrapped in a code span and their backticks and newlines removed first. An id reaches
# here from a git trailer, which is arbitrary text no gate has vetted -- and this feature exists
# for history that never passed those gates. Unescaped, an id beginning `<!--` sorts first under
# BINARY collation and comments out every row below it AND the count, in any renderer that
# passes HTML through. A report that its own input can silence is not a control. CHAR(96) rather
# than a literal backtick: this SQL sits in a double-quoted shell string, where a backtick opens
# a command substitution.
# All FOUR variable fields on this line are stripped; the id, the kinds and the path are also
# wrapped in a code span. The count matters: an earlier version of this comment said "every
# field" while meaning three, and the fourth -- the commit sha -- went out raw. A backtick and a
# newline injected into `commit_sha` then fabricated an extra bullet and moved the rendered count
# with it, because UNRESN below counts LINES, not rows. So the sha is stripped here too; it is
# not code-spanned only because it is already constrained to hex by everything that writes it,
# and `(no commit)` reads better unfenced.
#
# Why any of them: `kind` comes from a `Task-Status:` trailer that nothing checks against a
# vocabulary -- unlike `Via:`, which is checked -- the path comes from a filename, and the sha
# from an event row an ingest adapter may write directly. Hardening some fields and leaving the
# rest to the accident that the id sits first on the line is a fix that holds only until someone
# reorders the fields.
#
# `n.id IS NOT NULL` is not decoration either. The row is a concatenation, and a NULL anywhere
# in it makes the WHOLE row NULL: one NULL id would print a blank bullet, put the count out of
# step with the rows, and -- if it were the only unresolved id -- empty the section entirely
# while the escape residue below still fired. SQLite does not enforce NOT NULL on a TEXT PRIMARY
# KEY, which this file already hardened the residue query against and which the same commit then
# failed to apply to the query it was adding.
UNRES=$(q "SELECT CHAR(96)||REPLACE(REPLACE(REPLACE(n.id,CHAR(96),''),CHAR(10),' '),CHAR(13),' ')||CHAR(96)||'  '||
                  CASE WHEN EXISTS (SELECT 1 FROM event e WHERE e.task_id=n.id)
                    THEN REPLACE(REPLACE(REPLACE(
                           COALESCE((SELECT SUBSTR(e.commit_sha,1,7) FROM event e
                                      WHERE e.task_id=n.id AND e.commit_sha IS NOT NULL AND e.commit_sha<>''
                                      ORDER BY e.at, e.seq LIMIT 1),'(no commit)')
                           ,CHAR(96),''),CHAR(10),' '),CHAR(13),' ')
                         ||'  seen as: '||CHAR(96)||
                         REPLACE(REPLACE(REPLACE(
                           (SELECT GROUP_CONCAT(k) FROM
                              (SELECT DISTINCT e.kind AS k FROM event e
                                WHERE e.task_id=n.id AND e.kind IS NOT NULL ORDER BY e.kind))
                           ,CHAR(96),''),CHAR(10),' '),CHAR(13),' ')||CHAR(96)
                    ELSE 'declared by '||CHAR(96)||
                         REPLACE(REPLACE(REPLACE(
                           COALESCE((SELECT n2.path FROM edge d JOIN node n2 ON n2.id=d.src
                                      WHERE d.rel='depends_on' AND d.dst=n.id
                                        AND n2.path IS NOT NULL AND n2.path<>''
                                      ORDER BY n2.path LIMIT 1),'(unknown source)')
                           ,CHAR(96),''),CHAR(10),' '),CHAR(13),' ')||CHAR(96)
                  END
             FROM node n
            WHERE n.type='task'
              AND n.id IS NOT NULL
              AND NOT EXISTS (SELECT 1 FROM task t WHERE t.id=n.id)
            ORDER BY n.id;")
if [ -n "$UNRES" ]; then
  UNRESN=$(printf '%s\n' "$UNRES" | grep -c .)
  printf '\n## Unresolved task ids\n\n'
  printf '%s\n' "$UNRES" | sed 's/^/- /'
  printf '\n> **%s task id(s) are referenced but have no task file.** A reference is not a task,\n' "$UNRESN"
  printf '> so none of them is counted as open work or sits in any denominator above. One carrying\n'
  printf '> a commit came from a trailer — fix it there, or file the task. One declared by a file\n'
  printf '> came from that file’s `blocked_by:`, and is also withheld from the plan by `kit-plan`,\n'
  printf '> along with anything behind it. Either way it is named, not assumed.\n'

  # Dropping a completed task's history is deliberate; being unable to tell it happened is not.
  # This counts EVIDENCE and says so, rather than telling a story about a deleted file. The
  # earlier wording asserted "finished before the file went missing", which is wrong in both
  # directions and was caught in both: an id that was only ever a typo in a `Task-Status: done`
  # commit never had a file to lose, and a task closed in its frontmatter with no `Task-Status:`
  # trailer leaves no event here at all -- so the line claimed a deletion that never happened
  # while staying silent about one that did. Three lines above, this file concedes the evidence
  # is not reliable enough to interpret. It is not more reliable here.
  #
  # What can be said without inventing anything: these ids carry a recorded completion and back
  # no file, so whatever they closed is not in the counts above. Detecting a task file that was
  # genuinely DELETED needs git history in the indexer and is
  # T-20260809-a-deleted-task-file-is-indistinguishable.
  GONE=$(q "SELECT COUNT(*) FROM node n
             WHERE n.type='task'
               AND n.id IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM task t WHERE t.id=n.id)
               AND EXISTS (SELECT 1 FROM event e
                            WHERE e.task_id=n.id AND e.kind IN (SELECT a.written FROM state_alias a JOIN state_class c ON c.state=a.canonical WHERE c.is_closed = 1));")
  if [ "${GONE:-0}" -gt 0 ]; then
    printf '\n> **%s id(s) carry a recorded `done` or `abandoned`.** Whatever those closed is\n' "$GONE"
    printf '> not in the counts above — not in the done total, not in the escape-rate denominator\n'
    printf '> for their tier. If one had a task file, restoring it brings that history back. This\n'
    printf '> counts ids with a recorded closure and no file — which is a floor on THAT, and not a\n'
    printf '> count of deleted files in either direction: a task closed only in its frontmatter\n'
    printf '> leaves no event here, and an id that was only ever a typo never had a file to lose.\n'
  fi
fi

# Escape rate is the metric the whole tiering design rests on, and it has now been wrong in
# two opposite directions.
#
# It was first computed over EVERY task regardless of whether this pipeline had ever run on
# one. On a brownfield adoption most of the backlog is pre-existing or hand-done, so the
# denominator filled with work the kit never reviewed and the rate was diluted from the first
# day -- in the direction that makes tiering look ineffective.
#
# The fix was to compute it over via='kit' only, and that introduced a worse failure than the
# one it cured: filtering can make a recorded escape DISAPPEAR. Anything that moves a task out
# of `via='kit'` -- a kit command writing the column, a later `chore:` commit carrying
# `Via: manual`, a value nobody ever recorded -- removes its escapes from the only place
# escapes are ever surfaced. The `escaped` row stays in the database and the report reads zero.
#
# So both populations are reported and NEITHER is presented as the escape rate. The un-diluted
# number is what the filter was for and it is still here; the honest denominator is back beside
# it. Nothing is excluded from the report -- only from one of its two columns.
#
# That is what makes disappearance impossible by construction rather than by care. The `all`
# column has no WHERE clause, so it counts the escapes of every task in the index; the only
# escape it cannot reach is one attached to no task row at all, and that residue is counted
# separately below. The two are exhaustive: together they are `COUNT(*) WHERE kind='escaped'`.
printf '\n## Escape rate by tier\n\n'
printf '_Three populations, all reported, none of them alone "the escape rate". `via:kit` is work\n'
printf 'this pipeline actually ran, and omits everything it never saw. `measured` is every task that\n'
printf 'counts toward judging the pipeline — all of them except `cancelled`, which was never work.\n'
printf '`all` is the un-filtered denominator and has no WHERE clause at all, so nothing can vanish\n'
printf 'from it. Where `measured` and `all` differ, the difference is cancelled work._\n\n'
# Which vocabulary value means "this pipeline ran it", named once. The literal was already in
# two places here and splitting the rate into two columns would have made it four; an open
# finding on the provenance task calls out this file for hardcoding it, and while that finding
# is about deriving the value rather than repeating it -- which is that task's to decide -- one
# definition is strictly closer to it than four. The column label and the `Other provenance`
# heading are built from it, so neither can drift from what is actually being counted; the
# explanatory sentence above still says `via:kit` in prose, which is deliberate -- prose reads
# worse interpolated, and it is the one place a stale name is obvious rather than silent.
KITVIA=kit
# THREE POPULATIONS, AND THE MIDDLE ONE IS WHY `is_measured` EXISTS.
#
# `all` keeps NO WHERE CLAUSE, which is what makes disappearance impossible by construction
# rather than by care -- an earlier gate filtered `state='progress'` and hid two real criticals,
# so a filter here is not a free move. `measured` is the undiluted rate: it excludes states that
# are closed but were never work.
#
# The exclusion is STRUCTURAL, never `state <> 'cancelled'`. A literal would be a twentieth copy
# of the rule and would not follow the vocabulary the day another such state is added; joining
# state_class means the question "does this count toward judging the pipeline?" has exactly one
# answer, in kit-lib.sh. See docs/adr/0008.
#
# Why it matters, measured on a brownfield shape rather than argued: a census that files 200
# inventory items of which 120 are cancelled turns 5 escapes over 80 real tasks -- 6.25% -- into
# 5 over 200 -- 2.5%. The pipeline looks 2.5x better for having filed work that was never work.
#
# `all` IS ALWAYS PRINTED; `measured` APPEARS ONLY WHEN IT DIFFERS. The first draft had this the
# other way round and four conformance steps went red -- correctly. `all` is the anchor the report
# guarantees: the step named "nothing stored is missing from the report" pins its exact shape, and
# a rate that can drop the un-filtered denominator is one an escape can hide behind. `measured`
# says something new only when work has been excluded, which is only when something is cancelled;
# a permanently-equal second column trains a reader to skip both.
#
# NO `--` COMMENTS INSIDE THE QUERY STRING. `q()` passes this to sqlite3 as one argument, and a
# `--` comment swallowed the rest of the statement: the whole section rendered as "_no task
# recorded yet_", which reads as an empty backlog rather than as a broken query. Comments about
# SQL live in shell comments, above it.
ESC=$(q "SELECT printf('%-11s', COALESCE(NULLIF(t.tier,''),'untiered'))||
                printf('%-18s', SUM(CASE WHEN e.kind='escaped' AND t.via='$KITVIA' THEN 1 ELSE 0 END)||
                                ' / '||COUNT(DISTINCT CASE WHEN t.via='$KITVIA' THEN t.id END)||' via:$KITVIA')||
                CASE WHEN COUNT(DISTINCT CASE WHEN m.is_measured=1 THEN t.id END) = COUNT(DISTINCT t.id)
                     THEN ''
                     ELSE printf('%-20s', SUM(CASE WHEN e.kind='escaped' AND m.is_measured=1 THEN 1 ELSE 0 END)||
                                          ' / '||COUNT(DISTINCT CASE WHEN m.is_measured=1 THEN t.id END)||' measured')
                END||
                SUM(CASE WHEN e.kind='escaped' THEN 1 ELSE 0 END)||' / '||COUNT(DISTINCT t.id)||' all'||
                CASE WHEN COUNT(DISTINCT CASE WHEN m.is_measured=1 THEN t.id END) = COUNT(DISTINCT t.id)
                     THEN ''
                     ELSE '  ('||(COUNT(DISTINCT t.id) -
                                  COUNT(DISTINCT CASE WHEN m.is_measured=1 THEN t.id END))||' not measured)'
                END
         FROM task t LEFT JOIN event e ON e.task_id=t.id
                     LEFT JOIN state_class m ON m.state = t.state
         GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
[ -n "$ESC" ] && printf '%s\n' "$ESC" | sed 's/^/- /' || printf '_no task recorded yet_\n'

# An EMPTY DENOMINATOR is not a rate, and printed in the same shape as one it reads like a
# measurement. On 2026-08-11 this repository showed `0 / 0 via:kit` on all four tiers against 58
# tasks with nothing saying the column was empty -- the task's own stated defect ("a metric that
# cannot distinguish reviewed-and-nothing-escaped from never-reviewed") reintroduced in the new
# column. The older honest fallback above is unreachable, because ESC is grouped over every task
# and so is never empty merely because the kit population is.
#
# Said once, under the table, rather than per row: a reader who takes in four zeroes has already
# formed the impression this sentence exists to prevent.
#
# Gated PER TIER, not globally. A global count meant one `via:kit` task anywhere silenced the
# notice for every tier, so a tier with none went on printing `0 / 0` unexplained -- the defect
# surviving one level down, found in the review of 2026-08-12.
#
# Named tiers rather than a blanket sentence, because "some column somewhere is empty" is not
# something a reader can act on.
EMPTY_TIERS=$(q "SELECT group_concat(tier, ', ') FROM (
    SELECT COALESCE(NULLIF(t.tier,''),'untiered') AS tier
      FROM task t GROUP BY 1
    HAVING COUNT(DISTINCT CASE WHEN t.via='$KITVIA' THEN t.id END) = 0
     ORDER BY 1);")
if [ -n "$EMPTY_TIERS" ]; then
  printf '\n> **No task in %s records having been run by this pipeline.** The `0 / 0 via:%s`\n' \
    "$EMPTY_TIERS" "$KITVIA"
  printf '> against those tiers is an absent denominator, not a clean result: for them only the\n'
  printf '> `all` column is a measurement.\n'
fi

# The rest of the population, by value, WITH its escapes. Counting tasks alone was the older
# shape and it is exactly the one that reads clean: "12 excluded" says nothing about whether
# any of the twelve escaped. `unknown` is reported as itself and never folded into `manual` --
# they mean different things, and only one of them is a claim.
OTHER=$(q "SELECT printf('%-9s', t.via)||COUNT(DISTINCT t.id)||' task(s), '||
                  SUM(CASE WHEN e.kind='escaped' THEN 1 ELSE 0 END)||' escape(s)'
             FROM task t LEFT JOIN event e ON e.task_id=t.id
            WHERE t.via<>'$KITVIA'
            GROUP BY t.via ORDER BY 1;")
if [ -n "$OTHER" ]; then
  printf '\n**Other provenance** — in the `all` column above, not in `via:%s`\n\n' "$KITVIA"
  printf '%s\n' "$OTHER" | sed 's/^/- /'
  printf '\n> Provenance comes from a `Via:` trailer or a `via:` frontmatter key, and nothing in\n'
  printf '> the kit writes it for you — a model may propose it, a human confirms it.\n'
fi

# The residue: an escape whose task is not in the index at all. It is in neither column above,
# so it is the one way the report could still read zero while the database does not -- which
# makes saying it out loud the last piece of the guarantee, not a nicety.
#
# IT FIRES NOW. It could not when it was written: `kit-index.sh` invented a task row for any id
# it saw in a trailer, `Fixes-Escape-Of:` included, so the escape target always existed as an
# untiered `unknown` phantom and this branch was dead code covered by a seeded fixture. That
# invention was the filed defect T-20260808-a-task-id-matching-no-task-file-is-count, and
# removing it is exactly what brought this to life -- a guard written before the failure it
# guards against was reachable, which is the only order in which anyone actually writes one.
# Reproduced since: a commit carrying `Fixes-Escape-Of:` for an id with no task file now prints
# the line below. Conformance covers both the seeded state and the real one.
#
# `WHERE id IS NOT NULL` in the subquery is load-bearing and is not defensive habit. SQLite does
# not enforce NOT NULL on a TEXT PRIMARY KEY -- a documented deviation it keeps for backward
# compatibility -- so `task` can hold a NULL id, and `x NOT IN (set containing NULL)` is NULL for
# EVERY x, never true. One NULL id would therefore take this count to zero and hide every orphan,
# not just its own: the exact failure this whole block exists to rule out, arriving silently and
# through the guard against it. Measured, not reasoned: seeding one NULL-id row moved the residue
# from 1 to 0 and the filtered subquery restored it. `kit-index.sh` guards every insert into
# `task` against a blank id and is the only writer today, so this is unreachable through shipped
# code -- which is exactly what was true of the branch above, and is why it is written and tested
# rather than trusted. The invariant belongs in the schema as a CHECK; that is the missing-CHECK
# finding already open on T-20260808-record-how-a-task-was-executed-so-kit-wo, and closing it
# there does not make this line redundant, because this is the reader that makes the claim.
ORPH=$(q "SELECT COUNT(*) FROM event
           WHERE kind='escaped'
             AND (task_id IS NULL OR task_id=''
                  OR task_id NOT IN (SELECT id FROM task WHERE id IS NOT NULL));")
if [ "${ORPH:-0}" -gt 0 ]; then
  printf '\n> **%s recorded escape(s) belong to no task in this index.** A commit carried\n' "$ORPH"
  printf '> `Fixes-Escape-Of:` naming a task that has no file here, so the escape is real and\n'
  printf '> counted in neither column above. Fix the reference or restore the task file.\n'
fi

# Cost is a function of tier, and tier is assigned before anything spawns -- so a tiered
# backlog is already a forecast. This is the other half: what it actually cost.
#
# The rate is derived from THIS project's own closed tasks, not from a table shipped with the
# kit. A rate card from someone else's codebase forecasts someone else's codebase.
#
# THE UNIT. Every figure below is in billable input-token-equivalents -- the four counters
# weighted by what each is actually charged: fresh input 1x, cache write 1.25x, cache read
# 0.1x, output 5x. Those ratios hold across the Claude family, so one unit needs no rate card
# and no per-model configuration to go stale. Adding the counters raw instead prices a cache
# read like fresh input and reports seven times the truth; the harness's own subagent_tokens
# is a third thing again -- final context size, blind to work done. This is the only one of
# the three that is cost.
#
# It is deliberately not dollars. A single model's price list would date, and the ratios
# would not; where a project mixes model tiers the mix is printed rather than averaged away,
# because an opus token and a haiku token are the same size and not the same money.
# Scaled by 100 so the weights stay integers and the division happens once, on the total:
# dividing per row first and summing after loses a token per row to truncation.
BTE="(s.tok_in*100 + s.cache_write*125 + s.cache_read*10 + s.tok_out*500)"
# SPEND IS A MEASUREMENT, AND A MEASUREMENT MUST REPORT ITS OWN ABSENCE.
#
# This section used to be gated on `SPENT > 0` with no else, so an uninstrumented project and a
# project that genuinely cost nothing produced byte-identical reports. Measured on this
# repository: 0 spend rows after twelve days of heavy use, and not one mention of cost anywhere
# in the output. The `0 / 0 via:kit` family, and worse -- that one at least printed zeroes a
# reader could question.
#
# The sixteen OTHER sections gated this way are WARNINGS -- unresolved ids, orphan escapes,
# finding gaps, below-floor, the untagged threshold. A warning that stays quiet when there is
# nothing to warn about is correct, and they are deliberately left alone. Do not "fix" them.
# The distinction is whether absence of the section is itself information: for a measurement it
# always is.
SPENT=$(q "SELECT COUNT(*) FROM spend;")
if [ "${SPENT:-0}" -le 0 ]; then
  printf '\n## Spend\n\n'
  printf '> **Not recorded — this is not a measurement of zero.** The `spend` table is empty,\n'
  printf '> which almost always means the kit'"'"'s hooks were not active for the work: they fire\n'
  printf '> from `SubagentStop` and `Stop`, so a session run without the plugin loaded records\n'
  printf '> nothing. Cost figures for this project are UNAVAILABLE, not zero.\n>\n'
  printf '> Check with `kit-spend.sh --transcript <path>` on a known transcript; if that records\n'
  printf '> a row, the recorder is fine and the hooks are the thing to look at.\n'
fi
if [ "${SPENT:-0}" -gt 0 ]; then
  printf '\n## Spend\n\n'
  printf '_Billable input-token-equivalents: input x1, cache-write x1.25, cache-read x0.1, output x5._\n\n'
  ACT=$(q "SELECT COALESCE(NULLIF(t.tier,''),'untiered')||'  '||COUNT(DISTINCT s.task_id)||
                  ' task(s), '||(SUM($BTE)/100000)||'k, '||
                  (SUM($BTE)/COUNT(DISTINCT s.task_id)/100000)||'k mean'
             FROM spend s JOIN task t ON t.id=s.task_id
            WHERE s.task_id IS NOT NULL AND s.task_id<>''
            GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
  [ -n "$ACT" ] && printf '%s\n' "$ACT" | sed 's/^/- /'

  # Where the money went. The whole argument for a risk-tiered review pipeline is that the
  # reviewers are worth their tokens, and that is unarguable only while the two halves are
  # reported apart -- a single total lets an expensive review hide inside the work it checked.
  SCOPE=$(q "SELECT scope||'  '||COUNT(*)||' transcript(s), '||(SUM($BTE)/100000)||'k'
               FROM spend s GROUP BY scope ORDER BY 1;")
  [ -n "$SCOPE" ] && { printf '\n**By scope**\n\n'; printf '%s\n' "$SCOPE" | sed 's/^/- /'; }

  # And by provenance, because "did the kit pay for itself" is a comparison, and a comparison
  # needs both populations labelled. Spend attributed to a task this pipeline never ran is not
  # the kit's cost; folding it in flatters or damns the wrong thing.
  VIASPEND=$(q "SELECT t.via||'  '||COUNT(DISTINCT s.task_id)||' task(s), '||(SUM($BTE)/100000)||'k'
                  FROM spend s JOIN task t ON t.id=s.task_id
                 WHERE s.task_id IS NOT NULL AND s.task_id<>''
                 GROUP BY t.via ORDER BY 1;")
  [ -n "$VIASPEND" ] && { printf '\n**By provenance**\n\n'; printf '%s\n' "$VIASPEND" | sed 's/^/- /'; }

  MIX=$(q "SELECT COUNT(DISTINCT COALESCE(NULLIF(model,''),'?')) FROM spend;")
  if [ "${MIX:-0}" -gt 1 ]; then
    printf '\n> **%s models in this measurement.** The unit above counts tokens, not money,\n' "$MIX"
    printf '> so a total mixing model tiers understates the expensive ones. Per model:\n>\n'
    q "SELECT '> - '||COALESCE(NULLIF(s.model,''),'unknown')||'  '||(SUM($BTE)/100000)||'k'
         FROM spend s GROUP BY COALESCE(NULLIF(s.model,''),'unknown') ORDER BY SUM($BTE) DESC;"
  fi

  # Forecast the open backlog at this project's own measured mean per tier. Tiers with no
  # closed measurement are named rather than assumed -- an estimate that silently treats an
  # unmeasured tier as free is the failure this exists to avoid.
  EST=$(q "WITH rate AS (
             SELECT t.tier AS tier, SUM($BTE)/COUNT(DISTINCT s.task_id) AS per   -- x100
               FROM spend s JOIN task t ON t.id=s.task_id
              WHERE s.task_id IS NOT NULL AND s.task_id<>'' AND t.tier IS NOT NULL AND t.tier<>''
              GROUP BY t.tier)
           SELECT COALESCE(NULLIF(t.tier,''),'untiered')||'  '||COUNT(*)||' open x '||
                  COALESCE((SELECT (per/100000)||'k' FROM rate WHERE rate.tier=t.tier),'no rate yet')
             FROM task t WHERE t.state NOT IN (SELECT state FROM state_class WHERE is_closed = 1)
            GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
  if [ -n "$EST" ]; then
    printf '\n**Open backlog at this project'"'"'s measured rate**\n\n'
    printf '%s\n' "$EST" | sed 's/^/- /'
  fi

  # An UNSET task_id is not the only way spend can belong to nothing. A row naming an id with no
  # task row is dropped by every figure that JOINS `task` -- the per-tier table, By provenance,
  # and the rate card -- while a test for NULL alone never mentions it: neither attributed nor
  # reported, which is the third category this warning exists to prevent, arriving by the other
  # door. The indexer cannot produce it, since the id must resolve to a task before it is bound,
  # but an ingest adapter writes `spend` directly and section 4 preserves a pre-set value. Same
  # standing as the escape residue guard: unreachable through shipped code, counted anyway,
  # because the reader is where the claim is made.
  #
  # WHICH FIGURES, precisely -- an earlier version of this said "every figure above" and was
  # wrong. By scope and the model mix read `FROM spend` with no join, so they count this cost and
  # always did. That is correct for what they measure: they answer "where did the tokens go",
  # which is about transcripts and models, not about tasks. What was wrong was the sentence
  # printed below telling the reader it was excluded from figures that include it -- measured at
  # 1.4M of 1.5M reported. The number was never wrong; the claim about it was.
  UNATT=$(q "SELECT COUNT(*) FROM spend
              WHERE task_id IS NULL OR task_id=''
                 OR task_id NOT IN (SELECT id FROM task WHERE id IS NOT NULL);")
  if [ "${UNATT:-0}" -gt 0 ]; then
    printf '\n> **%s spend record(s) unattributed.** Either no task-status transition followed\n' "$UNATT"
    printf '> them, or the task they name has no file here — so they belong to no task. The work\n'
    printf '> happened and the cost is real: it is absent from the per-tier table, **By\n'
    printf '> provenance** and the rate card, which are per task — and PRESENT in **By scope**\n'
    printf '> and the per-model figures, which count transcripts and do not ask whose they were.\n'
  fi

  # Rows from before 0.8.0. Their numbers came from the session transcript while their label
  # named a subagent, so the cost is real and the attribution was not. Kept, stripped of the
  # label, and said out loud -- the same reason unattributed spend is reported rather than
  # dropped.
  LEG=$(q "SELECT COUNT(*) FROM spend WHERE scope='legacy';")
  if [ "${LEG:-0}" -gt 0 ]; then
    printf '\n> **%s spend record(s) predate per-agent measurement.** They were read from the\n' "$LEG"
    printf '> session transcript and cannot be attributed to any agent; their agent labels were\n'
    printf '> dropped at index time rather than believed.\n'
  fi
fi

# A subagent stopped and its transcript could not be found, so its cost was not recorded at
# all. Counted here because the alternative -- staying quiet -- is what makes a partial cost
# table read as cheap work rather than as measurement that did not happen.
GAP=$(q "SELECT COUNT(*) FROM event WHERE kind='spend-gap';")
if [ "${GAP:-0}" -gt 0 ]; then
  printf '\n> **%s subagent run(s) unmeasured.** No per-agent transcript was found when they\n' "$GAP"
  printf '> stopped, so nothing was recorded for them — not even a zero, which would have read\n'
  printf '> as free work.\n'
fi

# The findings equivalent, and the reason the loop is now closed rather than merely plumbed. A
# reviewer that emitted findings none of which were recorded is the exact failure this section
# exists to end: the table read zero and the README called it "nothing escaped". Emitted and
# recorded are BOTH shown, because the gap is the number that matters -- it is how the
# vocabulary problem gets measured instead of estimated at "roughly half".
# Counted, not summed: the generic event reader stores the WHOLE json line in `payload`, so the
# emitted/recorded numbers are inside a string rather than in columns. Extracting them here
# would mean parsing json in SQL to print a number this line does not need -- the count is the
# signal, and the detail is in events.ndjson where it was written.
# Split by reason, because the two mean opposite things and reporting them as one number is
# how "nothing was recorded" came to read as "nothing escaped". `empty` is EVIDENCE -- a review
# looked and found nothing. `rejected` is a HOLE -- findings existed and were refused, and they
# are now only in a reviewer nobody kept. The old single sentence described every gap as the
# second kind, which was wrong for the common case.
FGAPE=$(q "SELECT COUNT(*) FROM event WHERE kind='finding-gap' AND payload LIKE '%\"reason\":\"empty\"%';")
FGAPR=$(q "SELECT COUNT(*) FROM event WHERE kind='finding-gap' AND payload LIKE '%\"reason\":\"rejected\"%';")
FGAPO=$(q "SELECT COUNT(*) FROM event WHERE kind='finding-gap';")
FGAPU=$(( ${FGAPO:-0} - ${FGAPE:-0} - ${FGAPR:-0} ))
if [ "${FGAPR:-0}" -gt 0 ]; then
  printf '\n> **%s review(s) had findings REFUSED and therefore recorded none.** A batch is\n' "$FGAPR"
  printf '> rejected whole — for an unrecognised class or severity, or a malformed field — so\n'
  printf '> those findings exist only in the reply they came in. See `kit-finding.sh --vocab`\n'
  printf '> and `--contract`, which are the authoritative lists.\n'
fi
if [ "${FGAPE:-0}" -gt 0 ]; then
  printf '\n> **%s review(s) reported finding nothing.** That is a measurement, not a gap in\n' "$FGAPE"
  printf '> the record — it is counted here so an empty review stays distinguishable from a\n'
  printf '> review that never ran.\n'
fi
# Gaps written before the reason existed, named rather than folded into either meaning.
if [ "$FGAPU" -gt 0 ]; then
  printf '\n> **%s finding-gap event(s) carry no reason** and predate the split; they are\n' "$FGAPU"
  printf '> counted separately because guessing which kind they were would invent the number.\n'
fi

# OUTSTANDING CRITICALS. This section exists because the question "is there an open critical on
# this task" was UNCOMPUTABLE until `finding.fixed_at` did -- `vindicated` answers whether a
# finding was real, which is a different question, and no column answered this one. The trial
# protocol's first pre-flight box gated on it, could not be evaluated, and was waved through.
# A gate nobody can evaluate is worse than no gate, because it launders "we ignored it" into
# "we checked".
#
# Reported per TASK rather than as a total: the gate is per task, and one number cannot say
# which task is holding. A finding marked fixed leaves this list; a finding reopened returns to
# it. Nothing here is inferred -- an unmarked finding is OUTSTANDING, because assuming that
# silence means fixed is the failure this replaces.
# A FAILED QUERY IS NOT AN EMPTY RESULT, and this section shipped unable to tell them apart.
# `q()` sends stderr to /dev/null and yields "", so against an index built before `fixed_at`
# existed -- which the readability check at the top of this file passes, because `task` is
# still there -- the query errored, the empty string took the "none outstanding" branch, and
# the gate read clean. The critical its own T3 round found.
#
# Worse on inspection: that branch could never print at all. Its format string began with `-`,
# which bash printf parses as an option, so it errored to stderr and emitted nothing -- in the
# failure case AND in the ordinary case of a repository with genuinely zero open criticals. The
# line meant to say "none outstanding" had never once run. A control written against LESSONS S1
# that was itself S1.
#
# So: the exit status is READ, `--` ends option parsing, and the three states -- unreadable,
# none, some -- are three different pieces of output.
# A REFUTED critical is not outstanding work. `vindicated=0` means a reviewer was wrong, and
# there was no honest way to retire such a finding -- `--open`/`--fixed` say whether it was
# ADDRESSED, and "we did nothing because it was not a defect" is neither. It stays in the table,
# is excluded from the gate, and is counted below so the exclusion is visible rather than
# arithmetic nobody can see.
#
# COALESCE BEFORE THE COMPARISON, or SQL three-valued logic empties the gate: `vindicated` is
# NULL for most findings, `NULL = 0` is NULL, `NULL AND TRUE` is NULL, and `NOT NULL` is NULL --
# which is not TRUE, so every unjudged finding whose class is unique on its task silently left
# the count. Written without the COALESCE first and caught by the fixture, not by reading. It is
# the same NULL trap this file already carries two other fixes for.
#
# ONLY AN UNAMBIGUOUS REFUTATION RETIRES A FINDING. `kit-vindicate.sh` keys on (task, class) and
# updates every finding matching both, so on a task carrying two `fail-open` findings a single
# `--false` about the harmless one ALSO refutes the critical -- which would then leave this gate
# having never been judged. Excluded only when it is the sole finding of its class on its task.
# The same predicate lives in kit-preflight.sh --criticals, which is what the protocol runs.
UNAMBIG="1 = (SELECT COUNT(*) FROM finding g
               WHERE COALESCE(g.task_id,'') = COALESCE(f.task_id,'')
                 AND COALESCE(g.class,'')   = COALESCE(f.class,''))"
CRITFALSE=$(q "SELECT COUNT(*) FROM finding f
                WHERE f.severity='critical' AND f.fixed_at IS NULL AND f.vindicated=0
                  AND $UNAMBIG;")
CRITAMBIG=$(q "SELECT COUNT(*) FROM finding f
                WHERE f.severity='critical' AND f.fixed_at IS NULL AND f.vindicated=0
                  AND NOT $UNAMBIG;")
OPENCRIT=$(q "SELECT COALESCE(NULLIF(f.task_id,''),'(unattributed)')||'  '||COUNT(*)||
                     '  ['||COALESCE(NULLIF(t.state,''),'no task file')||']'
                FROM finding f LEFT JOIN task t ON t.id = f.task_id
               WHERE f.severity='critical' AND f.fixed_at IS NULL
                 AND f.unassessable_at IS NULL
                 AND f.superseded_at IS NULL
                 AND NOT (COALESCE(f.vindicated,1) = 0 AND $UNAMBIG)
               GROUP BY f.task_id ORDER BY COUNT(*) DESC;"); OCRC=$?
CRITTOT=$(q "SELECT COUNT(*) FROM finding f WHERE f.severity='critical' AND f.fixed_at IS NULL
              AND f.unassessable_at IS NULL
              AND f.superseded_at IS NULL
              AND NOT (COALESCE(f.vindicated,1) = 0 AND $UNAMBIG);")
# THE BLIND SPOT, COUNTED SEPARATELY AND NEVER FOLDED INTO ZERO. These left the gate because the
# operator marked each one individually as unjudgeable, with a reason -- not because a query
# stopped seeing them. Reported here for the same purpose the section exists: so "none
# outstanding" cannot be read as "nothing was ever wrong".
CRITUNASS=$(q "SELECT COUNT(*) FROM finding
                WHERE severity='critical' AND fixed_at IS NULL AND unassessable_at IS NOT NULL;")
# THE FOURTH DISPOSITION, COUNTED SEPARATELY FOR A DIFFERENT REASON THAN THE THIRD. An
# unassessable critical is a blind spot -- nobody can say what it was. A superseded one is the
# opposite: it is perfectly legible, it was REAL, and the subject it criticised was withdrawn
# because of it. Folding those into "fixed" would erase the most useful thing a review ever
# does, which is kill a design before it is built.
CRITSUPER=$(q "SELECT COUNT(*) FROM finding
                WHERE severity='critical' AND fixed_at IS NULL AND unassessable_at IS NULL
                  AND superseded_at IS NOT NULL;")
# CLOSING A TASK IS NOT FIXING ITS CRITICALS. The gate filtered `state='progress'`, so a
# critical on a done task did not count -- "fix it" and "close it" cleared the pre-flight
# equally. Counted and named here, because it is the direction that hides work.
CRITDONE=$(q "SELECT COUNT(*) FROM finding f JOIN task t ON t.id=f.task_id
               WHERE f.severity='critical' AND f.fixed_at IS NULL
                 AND f.unassessable_at IS NULL
                 AND f.superseded_at IS NULL
                 AND NOT (COALESCE(f.vindicated,1) = 0 AND $UNAMBIG) AND t.state IN (SELECT state FROM state_class WHERE is_closed = 1);")
CRITALL=$(q "SELECT COUNT(*) FROM finding WHERE severity='critical';")
printf '\n## Outstanding criticals\n\n'
if [ "$OCRC" != 0 ]; then
  printf -- '> **NOT MEASURED — the query failed.** This is not a report of zero. The usual\n'
  printf -- '> cause is an index built before `finding.fixed_at` existed: the readability check\n'
  printf -- '> at the top of this file passes on such a database because `task` is intact, and\n'
  printf -- '> only this section notices. Delete `%s` and run `kit-index.sh`.\n' "${DB#$ROOT/}"
elif [ -n "$OPENCRIT" ]; then
  printf '%s\n' "$OPENCRIT" | sed 's/^/- /'
  printf -- '\n_%s unfixed critical(s). The operator marks one addressed with\n' "${CRITTOT:-0}"
  printf -- '`kit-resolve.sh --finding ID --fixed`; `--list --severity critical --unfixed` prints the ids.\n'
  printf -- 'An agent proposes the mark and does not record it — clearing the gate that gates your\n'
  printf -- 'own work is the one certification the author cannot give._\n'
  if [ "${CRITDONE:-0}" != 0 ]; then
    printf -- '\n> **%s of them sit on a task that is already done or abandoned.** Closing a task\n' "$CRITDONE"
    printf -- '> does not address its criticals. They are counted here for that reason: the gate\n'
    printf -- '> used to look only at `progress`, so closing the task cleared it as effectively\n'
    printf -- '> as fixing the defect.\n'
  fi
else
  # Said explicitly. An empty section reads as "not measured" -- which is what this whole
  # section replaces -- and there is a real difference between no criticals and no marks.
  #
  # "all marked addressed" WAS A FALSE CLAIM and had been since unassessable_at was added: a
  # critical excluded as unjudgeable is not addressed, and one excluded as superseded is not
  # addressed either -- its subject died. The line printed the total and then asserted a
  # disposition for every row in it, which is the folding-into-zero this whole section exists to
  # prevent, in the one sentence a reader who stops at the first line will take away. It now
  # states only what is true and defers the rest to the notices below.
  _cother=$(( ${CRITUNASS:-0} + ${CRITSUPER:-0} ))
  if [ "$_cother" -gt 0 ]; then
    printf -- '- none actionable (%s critical finding(s) recorded; %s addressed, %s excluded — see below)\n' \
      "${CRITALL:-0}" "$(( ${CRITALL:-0} - _cother ))" "$_cother"
  else
    printf -- '- none outstanding (%s critical finding(s) recorded, all marked addressed)\n' \
      "${CRITALL:-0}"
  fi
fi

# OUTSIDE the branch above on purpose. If every remaining critical is unassessable the list is
# empty and the "none outstanding" line prints -- which is exactly when this notice matters most
# and exactly when a notice nested in the other branch would not appear.
if [ "${CRITUNASS:-0}" != 0 ]; then
  printf -- '\n> **%s critical(s) are excluded as UNASSESSABLE, and that is not the same as\n' "$CRITUNASS"
  printf -- '> fixed.** Each was marked individually by the operator with a recorded reason,\n'
  printf -- '> because what the finding said cannot be recovered from what survives — most of\n'
  printf -- '> them predate the `summary` column. They are out of the pre-flight gate and still\n'
  printf -- '> in the record, permanently. `kit-resolve.sh --list --severity critical` shows\n'
  printf -- '> them with their reasons.\n'
  printf -- '>\n'
  printf -- '> Read the count above as "%s actionable, %s unjudgeable" rather than as a total.\n' \
    "${CRITTOT:-0}" "$CRITUNASS"
fi

# OUTSIDE the branch too, and for the reason the unassessable notice is: this matters most when
# the list is empty, which is exactly when a nested notice would not print.
if [ "${CRITSUPER:-0}" != 0 ]; then
  printf -- '\n> **%s critical(s) are excluded as SUPERSEDED, and that is not the same as\n' "$CRITSUPER"
  printf -- '> fixed either.** Nothing was fixed: the subject each one criticised was withdrawn,\n'
  printf -- '> rejected or replaced, and each mark names what withdrew it. The subject file\n'
  printf -- '> itself carries a matching `Superseded-by:` line — `kit-resolve.sh` refuses the\n'
  printf -- '> mark without one, so this exclusion cannot be reached by assertion alone.\n'
  printf -- '>\n'
  printf -- '> **These were REAL, and being real is why the subject died.** That is the most\n'
  printf -- '> valuable thing a review does, so it is counted here rather than folded into a\n'
  printf -- '> total that would read as though the defects had been repaired.\n'
fi

# Marks that did NOT apply. The indexer used to say this on stderr alone, where a run inside
# kit-status.sh, a hook or CI is read by nobody -- so the list above could be short for the one
# reason that must never be silent: the evidence failed to land. Each count is a different
# failure and they are not summed.
# AN ABSENT COUNTER IS NOT A ZERO COUNTER. These are read with `${x:-0}`, and an index built
# before they existed has no such key -- so the empty string became 0 and the file asserted
# that no mark had failed to apply. The same fail-open as this section's own critical, one level
# down, introduced by the fix for it. The keys are written unconditionally by kit-index.sh now,
# so their ABSENCE means a stale index and is reported as one.
FORPH=$(q "SELECT value FROM meta WHERE key='finding_orphan_marks';")
FAMB=$(q "SELECT value FROM meta WHERE key='finding_ambiguous_marks';")
FCOLL=$(q "SELECT value FROM meta WHERE key='finding_id_collisions';")
FMISS=$(q "SELECT value FROM meta WHERE key='finding_fix_commit_missing';")
if [ -z "$FORPH" ] || [ -z "$FAMB" ] || [ -z "$FMISS" ] || [ -z "$FCOLL" ]; then
  printf -- '\n> **Mark-failure counters are ABSENT from this index, not zero.** It was built\n'
  printf -- '> before they existed, so whether any mark failed to apply is unknown here. Delete\n'
  printf -- '> `%s` and run `kit-index.sh`.\n' "${DB#$ROOT/}"
fi
if [ "${FMISS:-0}" != 0 ]; then
  printf -- '\n> **%s fix mark(s) name a commit that is not in this history.** The finding reads\n' "$FMISS"
  printf -- '> as addressed and its evidence resolves to nothing — a rebased branch, or a SHA\n'
  printf -- '> that never existed. Note that a REVERTED fix is NOT detected: its commit is still\n'
  printf -- '> there, so the mark still resolves and still reads as addressed.\n'
fi
if [ "${CRITAMBIG:-0}" != 0 ]; then
  printf -- '\n> **%s unfixed critical(s) carry a refutation that cannot be trusted.** They are\n' "$CRITAMBIG"
  printf -- '> COUNTED above, not excluded. `kit-vindicate.sh` keys on `(task, class)` and marks\n'
  printf -- '> every finding matching both, so on a task with two findings of one class a single\n'
  printf -- '> `--false` about the harmless one also refutes the critical. A refutation retires a\n'
  printf -- '> finding only when it is the sole finding of its class on its task.\n'
fi
if [ "${CRITFALSE:-0}" != 0 ]; then
  printf -- '\n> **%s unfixed critical(s) are excluded as refuted** (`vindicated=0`). A reviewer\n' "$CRITFALSE"
  printf -- '> was wrong, so there is nothing to address — but they are named here rather than\n'
  printf -- '> silently dropped, because an exclusion nobody can see is indistinguishable from a\n'
  printf -- '> count that is simply wrong.\n'
fi
if [ "${FORPH:-0}" != 0 ]; then
  printf -- '\n> **%s finding-fixed mark(s) name no known finding and were NOT applied.** The\n' "$FORPH"
  printf -- '> finding they point at is not in this index, so whatever they record is not\n'
  printf -- '> reflected above. An id is content-derived; a mark that resolves to nothing was\n'
  printf -- '> written against a different log, or by hand.\n'
fi
if [ "${FAMB:-0}" != 0 ]; then
  printf -- '\n> **%s finding-fixed mark(s) were REFUSED as ambiguous.** Two different events hash\n' "$FAMB"
  printf -- '> to one id, so the mark cannot be attached to one of them without guessing which.\n'
  printf -- '> It is withheld rather than applied: a mark on the wrong finding asserts that a\n'
  printf -- '> specific defect was fixed, which is worse than no mark at all.\n'
fi
if [ "${FCOLL:-0}" != 0 ]; then
  printf -- '\n> **%s finding id collision(s).** Distinct events sharing an id. Both rows are kept\n' "$FCOLL"
  printf -- '> and both are listed, but marks on them are refused per the notice above.\n'
fi

# Findings the attribution heuristic could not bind to a task. Same standing as unattributed
# spend: the work was reviewed and the finding is real, so it is named rather than dropped from
# the count it should have been in.
FUNATT=$(q "SELECT COUNT(*) FROM finding
             WHERE task_id IS NULL OR task_id=''
                OR task_id NOT IN (SELECT id FROM task WHERE id IS NOT NULL);")
if [ "${FUNATT:-0}" -gt 0 ]; then
  printf '\n> **%s finding(s) unattributed.** No task-status transition followed them, or the\n' "$FUNATT"
  printf '> task they bound to has no file here — so they are in no per-task or per-tier figure.\n'
fi

# Under-tiering is silent and it is the dangerous direction: a task recorded T1 that should
# be T2 gets one fewer reviewer and nothing says so. Measured on a real backlog, two of three
# recorded tiers were below their floor -- both because the backlog was tiered from finding
# SEVERITY rather than checked against the project's own tier.rule globs.
#
# Escape rate by tier is computed from these same values, so a wrong tier does not make that
# metric noisy. It makes it wrong in a direction that still looks calibrated.
BELOW=$(q "SELECT t.id||'  recorded '||COALESCE(NULLIF(t.tier,''),'(none)')||', floor '||t.tier_floor
             FROM task t
            WHERE t.tier_floor IS NOT NULL
              AND (t.tier IS NULL OR t.tier='' OR t.tier < t.tier_floor)
              AND t.state NOT IN (SELECT state FROM state_class WHERE is_closed = 1)
            ORDER BY t.tier_floor DESC, t.id;")
if [ -n "$BELOW" ]; then
  printf '\n## Below their tier floor\n\n'
  printf '%s\n' "$BELOW" | sed 's/^/- /'
  printf '\n_A floor raises and never lowers. Reviewed one rung shallow until corrected._\n'
fi

# Silence on an unjudgeable task is how under-tiering stays invisible, so say how much of the
# backlog the check could not speak for rather than letting it read as a clean bill.
NOBASIS=$(q "SELECT COUNT(*) FROM task WHERE tier_floor IS NULL AND state NOT IN (SELECT state FROM state_class WHERE is_closed = 1);")
OPENN=$(q "SELECT COUNT(*) FROM task WHERE state NOT IN (SELECT state FROM state_class WHERE is_closed = 1);")
if [ "${NOBASIS:-0}" -gt 0 ]; then
  printf '\n> **Tier floors unverified for %s of %s open task(s).** No declared `paths:` and no\n' "$NOBASIS" "$OPENN"
  printf '> files touched yet, so no floor could be computed — not that none applies.\n'
fi

# A rule the indexer refused is the OTHER reason a floor can be missing, and without this the
# message above claims the benign one — "nothing to go on" — about a task that declared its
# paths and had them judged by a rule that was thrown away. The indexer says this on stderr
# too, but kit-status.sh runs it with stderr discarded, so the terminal warning reaches nobody
# and the file is what gets read.
# A path git would only give us quoted -- one containing a double quote, a backslash or a
# control byte -- is dropped rather than recorded under a name that matches no rule. That is
# the same "missing floor" the message above describes, arriving by a different route, and it
# has to be said for the same reason: the benign cause must not stand in for this one.
UNUSABLE=$(q "SELECT value FROM meta WHERE key='paths_unusable';")
case "${UNUSABLE:-0}" in ''|0) ;; *)
  printf '\n> **%s changed path(s) could not be indexed.** git only reports a name containing a\n' "$UNUSABLE"
  printf '> quote, a backslash or a control byte in escaped form, and a floor derived from that\n'
  printf '> name would match nothing — so those files carry no `touches` edge and no floor here.\n'
  printf '> Blast radius and tier floor are therefore incomplete for them, not clean.\n' ;;
esac

REFUSED=$(q "SELECT value FROM meta WHERE key='tier_rules_refused';")
case "${REFUSED:-0}" in ''|0) ;; *)
  printf '\n> **%s `tier.rule` line(s) refused as unusable, so their floor never applied:**\n' "$REFUSED"
  printf '> `%s`\n' "$(q "SELECT value FROM meta WHERE key='tier_rules_refused_text';")"
  printf '> A refused rule is not an absent one — any "unverified" above may be this, not a\n'
  printf '> task with nothing to go on. Fix the glob in `.claude/project-profile.md`.\n' ;;
esac

# ---- the plan (ADR 0004) -----------------------------------------------------------------
# Two conditions, and they are different failures said differently. A STALE plan loaded fine
# and describes a backlog that has moved. An ORPHANED pack directory has no plan at all behind
# it and is the shape the whole ADR is about: before the plan was persisted, every kit-index.sh
# run left exactly this -- pack files on disk, looking current, that skills/task-context would
# never load because its step 4 finds no row.
# A REFUSED plan is reported first and by name. It used to be reported as an orphaned pack —
# zero rows loaded looks identical to no plan written — which is the wrong cause and the wrong
# remedy, and after a merge it is the EXPECTED state, because .gitattributes deliberately
# declines merge=union so two plans conflict rather than interleave.
# The cluster-size distribution. It was absent, so a 70-of-85 cluster could only be found by
# querying plan_item by hand — which is how it went unnoticed while the packs built from it were
# being proposed as the subject of an ROI experiment.
q "SELECT substr(key,21)||' '||value FROM meta WHERE key LIKE 'cluster_largest_pct:%';" | tr -d '\r' |
while IFS=' ' read -r _g _pct; do
  [ -n "$_g" ] || continue
  printf '\n> **Largest cluster in `%s` holds %s%% of its planned tasks.**' "$_g" "$_pct"
  if [ "${_pct:-0}" -gt 60 ]; then
    printf ' Packs are **withheld** —\n'
    printf '> a pack built from a cluster that size names most of the repository, which is worse\n'
    printf '> than no pack. The ordering is unaffected: layers come from topology and ranks from\n'
    printf '> score. Raise `cluster.max_share` to accept it, or fix the grouping.\n'
  else
    printf '\n'
  fi
done

# A gitignored plan is the quietest way to undo this whole mechanism: everything works on the
# machine that planned, and the guarantee ADR 0004 publishes is false everywhere else.
q "SELECT substr(key,14) FROM meta WHERE key LIKE 'plan_ignored:%';" | tr -d '\r' |
while IFS= read -r _g; do
  [ -n "$_g" ] || continue
  printf '\n> **The plan for `%s` is covered by `.gitignore`.** It will not survive a clone, a\n' "$_g"
  printf '> new machine, or a deleted index — which is the machine-local state ADR 0004 exists to\n'
  printf '> abolish, arriving through configuration rather than code. Everything looks correct\n'
  printf '> here and is absent for everyone else. Un-ignore `.project/plans/`.\n'
done

PLANREF=$(q "SELECT value FROM meta WHERE key='plan_refused';")
case "${PLANREF:-0}" in ''|0) ;; *)
  printf '\n> **%s plan file(s) were parsed and REFUSED, so their ordering is not loaded:**\n' "$PLANREF"
  printf '> `%s`\n' "$(q "SELECT value FROM meta WHERE key='plan_refused_text';")"
  printf '> A refused plan is not an absent one. Conflict markers from a merge are the usual\n'
  printf '> cause — the plan is deliberately not `merge=union`, so two orderings conflict\n'
  printf '> rather than silently interleaving. Resolve the file, or re-run `kit-plan.sh`.\n' ;;
esac

# `while IFS= read -r`, not `for _g in $(...)`. A goal id reaches this loop from a committed
# plan file, and an unquoted command substitution word-splits and globs it: a goal named `*`
# expanded local filenames into this report. kit-index.sh names that exact shape as the one
# LESSONS §4 says to sweep for, and SECURITY.md §5 forbids it.
q "SELECT substr(key,12) FROM meta WHERE key LIKE 'plan_stale:%';" | tr -d '\r' |
while IFS= read -r _g; do
  [ -n "$_g" ] || continue
  printf '\n> **The plan for `%s` was computed from a different backlog.** Tasks have been\n' "$_g"
  printf '> added, closed, re-tiered or re-blocked since it was written, so its ordering may name\n'
  printf '> work that no longer exists and omit work that does. It is still loaded and still\n'
  printf '> readable — this is a notice, not a withdrawal. Re-run `kit-plan.sh` to refresh it.\n'
done

# The INVERSE of the orphan check below, and the one a fresh clone actually hits: the plan is
# committed and the packs are gitignored, so a clone arrives with rows and no pack — and
# skills/task-context step 4 builds a path from the row and reads nothing. Silent before; the
# skill has no miss branch, so the agent simply got less context than it was told it had.
MISSINGPACKS=""
q "SELECT DISTINCT goal_id FROM plan_item;" | tr -d '\r' |
while IFS= read -r _g; do
  [ -n "$_g" ] || continue
  # A goal whose packs were WITHHELD is not a goal whose packs are missing. The notice above
  # already names the cause; repeating it here as "run kit-plan.sh --packs" would send the
  # reader to a remedy that refuses for the same reason — wrong cause, wrong remedy, which is
  # the defect a T3 security review flagged when a refused plan was reported as an orphan.
  [ "$(q "SELECT COUNT(*) FROM meta WHERE key='cluster_packs_withheld:$(printf '%s' "$_g" | sed "s/'/''/g")';")" = 0 ] || continue
  [ -d "$ROOT/$STATE_DIR/packs/$_g" ] || printf '%s\n' "$_g"
done > "$OUT.missingpacks" 2>/dev/null
if [ -s "$OUT.missingpacks" ]; then
  printf '\n> **Plan row(s) with no cluster pack on disk:** %s\n' "$(tr '\n' ' ' < "$OUT.missingpacks")"
  printf '> A fresh clone looks exactly like this — the plan is committed and the packs are not.\n'
  printf '> `skills/task-context` step 4 will build a pack path from the plan row and find\n'
  printf '> nothing there. Rebuild them from the plan you already have, which does NOT recompute\n'
  printf '> the ordering:  `bash tooling/kit-plan.sh --packs`\n'
fi
rm -f "$OUT.missingpacks"

if [ -d "$ROOT/$STATE_DIR/packs" ]; then
  ORPHANED=""
  for _pd in "$ROOT/$STATE_DIR/packs"/*; do
    [ -d "$_pd" ] || continue
    _pg=${_pd##*/}
    _n=$(q "SELECT COUNT(*) FROM plan_item WHERE goal_id='$(printf '%s' "$_pg" | sed "s/'/''/g")';")
    case "${_n:-0}" in 0) ORPHANED="$ORPHANED $_pg" ;; esac
  done
  # Suppressed when a plan was refused: those packs have a plan, it just did not load, and the
  # notice above already names the real cause. Reporting "re-run kit-plan.sh, or delete them"
  # over a conflicted file sends the reader to the wrong remedy.
  if [ -n "$ORPHANED" ] && [ "${PLANREF:-0}" = 0 ]; then
    printf '\n> **Cluster pack(s) on disk with no plan behind them:**%s\n' "$ORPHANED"
    printf '> A pack is a cache of a plan. With no `plan_item` row, `skills/task-context` step 4\n'
    printf '> finds nothing and never reads them — so these are resident cost returning nothing,\n'
    printf '> not context anybody is being served. Re-run `kit-plan.sh`, or delete them.\n'
  fi
fi

if [ "$REQUIRED" -gt 0 ] && [ $(( UNTAG * 100 / REQUIRED )) -gt 20 ]; then
  printf '\n> **Trailer discipline degraded.** %s of %s non-trivial commits carry no `Task-Id`' "$UNTAG" "$REQUIRED"
  [ "$EXEMPTN" -gt 0 ] && printf ' (%s trivial commit(s) excluded per `git.trivial_pattern`)' "$EXEMPTN"
  printf '.\n'
  printf '> Derived status under-reports; an empty backlog here may be a measurement failure, not an idle repo.\n'
fi
} > "$OUT"
echo "${OUT#$ROOT/}"
