#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Raghuveer Dendukuri
# kit-init.sh — adopt the kit in the current repository. Idempotent.
set -euo pipefail
ROOT=$(git rev-parse --show-toplevel) || { echo "not a git repository" >&2; exit 1; }
HERE=$(cd "$(dirname "$0")" && pwd)
# Sourced for kit_cfg: the .gitignore lines below must honour paths.state rather than assume
# .project, and this script had no profile reader until then.
. "$HERE/kit-lib.sh"

mkdir -p "$ROOT/.claude" "$ROOT/.project/tasks"

if [ -f "$ROOT/.claude/project-profile.md" ]; then
  ADOPTED=1
  echo "profile exists, left alone"
else
  ADOPTED=0
  # tr, not cp: this writes a file into someone else's repository, and it must land the same
  # on every platform. `cp` copies the plugin checkout's bytes verbatim, so a kit fetched with
  # core.autocrlf=true -- or unpacked from an archive built on Windows -- seeded a CRLF
  # profile that then travelled to a colleague on Linux. The kit's own .gitattributes pins
  # *.md to LF, which fixes the git path and not the archive path; this fixes both.
  tr -d '\r' < "$HERE/../templates/project-profile.md" > "$ROOT/.claude/project-profile.md"
  echo "created .claude/project-profile.md  <- fill this in; the kit is inert until you do"
fi

# Generate rather than symlink: the plugin's location is machine-specific, and the hooks
# directory is never shared by git. Each developer regenerates their own.
#
# Ask git where hooks live rather than assuming $ROOT/.git/hooks. `.git` is a FILE in a
# linked worktree or a submodule, and core.hooksPath relocates the directory outright.
# Guessing wrong writes a hook git never runs, so commits pass unvalidated while the repo
# looks protected -- the fail-open case commit-msg exists to prevent, one level up.
HOOKS=$(cd "$ROOT" && git rev-parse --git-path hooks)
HOOKS=$(cd "$ROOT" && mkdir -p "$HOOKS" && cd "$HOOKS" && pwd)   # relative or absolute
# Compare in one path form. git reports C:/... on Windows while pwd reports /c/..., so a
# naive ${HOOK#$ROOT/} never matches and prints a full absolute path instead. In a linked
# worktree the hook genuinely sits outside $ROOT, and there it stays absolute on purpose.
ROOT_P=$(cd "$ROOT" && pwd)

# gen_hook <name> -- write one hook, preserving anything already there.
#
# An existing hook is someone's tooling -- husky, commitlint, a team script. Truncating it
# is not idempotence, it is data loss. Git runs only ONE hook of each name, so the old one
# stops firing either way; back it up and make that the operator's decision, not a silent
# side effect of adopting the kit.
gen_hook() {
  _name=$1
  _hook="$HOOKS/$_name"
  if [ -e "$_hook" ] && ! grep -q 'GENERATED by kit-init.sh' "$_hook" 2>/dev/null; then
    _bak="$_hook.pre-kit"
    if [ -e "$_bak" ]; then _bak="$_hook.pre-kit.$(date -u +%Y%m%d%H%M%S)"; fi
    cp "$_hook" "$_bak"
    echo "WARNING: existing $_name hook saved as ${_bak##*/}"
    echo "         it no longer runs — chain it from the generated hook if you still need it"
  fi
  {
    printf '#!/usr/bin/env bash\n'
    printf '# GENERATED by kit-init.sh -- re-run it if the plugin moves.\n'
    printf 'export KIT_TOOLING=%q\n' "$HERE"
    tail -n +2 "$HERE/$_name"
  } > "$_hook"
  chmod +x "$_hook"
  echo "generated ${_hook#$ROOT_P/} (tooling: $HERE)"
}

gen_hook commit-msg
# pre-push is the last point a wrong trailer can still be amended. commit-msg is skippable
# with --no-verify and absent for anyone who never ran this script; CI catches it correctly
# but only after the push, when the commit message can no longer be changed.
gen_hook pre-push
if [ -n "$(git -C "$ROOT" config --get core.hooksPath 2>/dev/null || true)" ]; then
  echo "note: core.hooksPath is set, so the hook went there rather than .git/hooks"
fi

# The index is derived. Committing it would create a second source of truth and an
# unresolvable binary merge conflict for every developer on the repo.
GI="$ROOT/.gitignore"
# `index.db*`, not `index.db`: the indexer builds into `index.db.new` and marks a failed build
# with `index.db.failed`, and an EXIT trap cannot fire on a kill or a power loss. An
# exact-match ignore left those untracked, where the next `git add -A` stages a derived
# database into a repository whose ignore comment says never to commit one.
grep -qxF '.project/index.db*' "$GI" 2>/dev/null || printf '\n# derived, rebuildable — never commit\n.project/index.db*\n' >> "$GI"
grep -qxF 'STATUS.generated.md' "$GI" 2>/dev/null || echo 'STATUS.generated.md' >> "$GI"
# Cluster packs are a snapshot of the index for one plan. Committing them would put a
# stale copy of derived state in the repo — the second-truth problem this design avoids.
#
# `.project/plans/` is deliberately NOT added here, and the distinction is the whole of ADR
# 0004: a pack is a rebuildable CACHE of the plan, and the plan is the decision it caches.
# Ignoring the plan is what made it machine-local, and machine-local state that no text
# rebuilds is exactly what kit-index.sh dropped on every run. If you are adding an ignore line
# for it, read that ADR first — the packs beside it are the ones that belong here.
grep -qxF '.project/packs/' "$GI" 2>/dev/null || echo '.project/packs/' >> "$GI"
# kit-entry.sh's four artefacts, for the same reason and one more: they are a snapshot of ONE
# machine's working copy at one moment, and nothing detects them going stale against the tree.
# This was found by a fixture rather than by inspection -- the adoption .gitignore did not carry
# these lines, so a subject's next `git add -A` committed the report and the facts table, which
# then changed the commit count the report itself derives. A derived artefact that alters the
# measurement it reports is the second-truth problem with a feedback loop attached.
# paths.state, not a hardcoded .project: kit-entry.sh writes into whatever the profile declares,
# so a subject that configured a different state directory would have had these committed.
_ST=$(kit_cfg "$ROOT/.claude/project-profile.md" paths.state ".project")
# THREE, NOT FOUR. `entry-candidates.md` was in this list and is deliberately NOT ignored any
# more: kit-entry.sh does not write it -- the model does, following docs/ENTRY-PROPOSAL.md -- so
# it is a PROPOSAL a human reviews rather than derived output, and a re-run cannot reproduce the
# same judgement the way it reproduces a census.
#
# Caught by running kit-init.sh on this repository AFTER the un-ignore: the line was appended
# straight back, silently. This loop only ever ADDS, so a deliberate removal survives exactly
# until the next kit-init.sh -- including for an adopter who ran it for an unrelated reason. An
# append-only writer over a file a human also edits reverts decisions without saying so.
for _e in entry-facts.tsv entry-comment-runs.tsv entry-report.md; do
  grep -qxF "$_ST/$_e" "$GI" 2>/dev/null || echo "$_ST/$_e" >> "$GI"
done
echo "updated .gitignore"

# events.ndjson is append-only and shared. Without a union merge, two developers
# appending on the same day produce a conflict on every pull. Union takes both sides;
# ordering does not matter because the indexer sorts by timestamp.
GA="$ROOT/.gitattributes"
grep -q 'events.ndjson' "$GA" 2>/dev/null || \
  printf '\n# append-only shared log: take both sides rather than conflicting\n.project/events.ndjson merge=union\n' >> "$GA"
echo "updated .gitattributes (events.ndjson merge=union)"

# The plan (ADR 0004) is committed and READ AS DATA by kit-index.sh, so a CRLF checkout would
# carry a CR into the goal id and the task digest -- which would mark every plan stale against
# itself, quietly. Deliberately NOT merge=union like the log above: two people planning the
# same goal produced two orderings, and taking both sides interleaves them into a third that
# neither computed. A conflict here is a disagreement about what to do next and belongs in
# front of a person.
# Exact line, not a substring. `grep -q 'plans/'` matched any unrelated attribute an adopted
# repo already had (`plans/*.pdf binary` is enough) and silently suppressed the pin — while the
# success line below printed anyway, telling the operator a protection was in place when it was
# not. The failure then surfaces as every plan reading stale against itself.
if grep -qxF '.project/plans/*.tsv text eol=lf' "$GA" 2>/dev/null; then
  echo ".gitattributes already pins the plan to LF"
else
  printf '\n# the plan: read as data, so pin the line endings. NOT merge=union -- see ADR 0004\n.project/plans/*.tsv text eol=lf\n' >> "$GA" &&
    echo "updated .gitattributes (plans pinned to LF)" ||
    kit_warn "could not pin .project/plans/*.tsv to LF in .gitattributes"
fi

echo
if [ "$ADOPTED" = 1 ]; then
  # Joining an existing project. Git does not share hooks, so this step is what a new
  # team member is actually here for; the shared config arrived with the clone.
  echo "joined an already-adopted repo. Hook is now wired locally."
  echo "  next: kit-index.sh   (rebuilds your local index from the repo's task files + trailers)"
else
  echo "next:"
  echo "  1. fill in commands.* and tier.rule in .claude/project-profile.md"
  echo "  2. append templates/CLAUDE.kit.md to your CLAUDE.md"
  echo "  3. commit .claude/project-profile.md and .project/tasks/ — the team shares them"
  echo "  4. delete any hand-maintained STATUS.md or task CSV — a surviving copy WILL be edited"
  # The hook only protects developers who ran this script. Git cannot share .git/hooks, so
  # for anyone who skipped it there is no enforcement at all and the repo merely looks
  # protected. Server-side is the only check that survives a clone.
  echo "  5. copy templates/github-trailer-gate.yml to .github/workflows/ — the hook is"
  echo "     per-clone, so CI is the only trailer check that survives someone skipping it"
fi
